# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: 0.21 #.5
epsilon_finish: 0.2 # .01
epsilon_anneal_time: 1 # 100000
mask_before_softmax: False

runner: "episode"

buffer_size: 5000 # 8 # size of the replay buffer
# batch_size_run: 1 # number of environments to run in parallel
# batch_size: 32 # 8   # batch size

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

# lr: 0.0005
# critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "coma"
