# --- MAPPO specific parameters ---

# action_selector: "soft_policies"
# mask_before_softmax: True
action_selector: "epsilon_greedy"
epsilon_start: 0.21 # 1
epsilon_finish: 0.2 # 0/05
epsilon_anneal_time: 1 # 500000

runner: "episode"

buffer_size: 5000 # 10
# batch_size_run: 1 # 10
# batch_size: 32 # 8 # 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0005

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.01
use_rnn: False
standardise_returns: True
standardise_rewards: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "mappo"

# t_max: 20050000
hidden_dim: 64
add_value_last_step: True